SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `workfit`.`calendar_special _days` 
DROP COLUMN `DATE_DAY`,
CHANGE COLUMN `TYPE_DAY` `TYPE_DAY` INT(11) NOT NULL ,
CHANGE COLUMN `DESCRITION` `DESCRITION` VARCHAR(1000) NULL DEFAULT NULL ,
ADD COLUMN `YEAR_ID` INT(11) NOT NULL AFTER `DESCRITION`,
ADD COLUMN `YEAR_DAY_NUMBER` INT(11) NOT NULL AFTER `YEAR_ID`,
ADD INDEX `fk_calendar_special _days_year1_idx` (`YEAR_ID` ASC);

ALTER TABLE `workfit`.`calendar_special _days` 
ADD CONSTRAINT `fk_calendar_special _days_year1`
  FOREIGN KEY (`YEAR_ID`)
  REFERENCES `workfit`.`year` (`YEAR_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
