SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `WorkFit`.`SPENT_HOLIDAY` 
DROP FOREIGN KEY `fk_SPENT_HOLIDAY_MONTH1`;

ALTER TABLE `WorkFit`.`DAYS_OF_WORK` 
DROP FOREIGN KEY `fk_DAYS_OF_WORK_MONTH1`;

ALTER TABLE `WorkFit`.`MONTH` 
RENAME TO  `WorkFit`.`MONTHS` ;

ALTER TABLE `WorkFit`.`SPENT_HOLIDAY` 
ADD CONSTRAINT `fk_SPENT_HOLIDAY_MONTH1`
  FOREIGN KEY (`MONTH_ID`)
  REFERENCES `WorkFit`.`MONTHS` (`MONTH_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `WorkFit`.`DAYS_OF_WORK` 
ADD CONSTRAINT `fk_DAYS_OF_WORK_MONTH1`
  FOREIGN KEY (`MONTH_ID`)
  REFERENCES `WorkFit`.`MONTHS` (`MONTH_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
